### ISSUE TITLE
As a User I can see shopping places in a destination

### ISSUE THREAD

**Issue by ystamaritq** [CB-Group-6-Project-1/travel-board#22]
- [x] Develop a js function to **load shopping places** for a given **input city**.
- [x] Develop the functionality to display the **shopping places** of the city.

-  Reference User Interfaces` "City Details Page" (Shopping) `

**Comment by JDMartinez1531** [comment]
Used boundary box from city query to search for locations under the category "shopping." Displayed to shopping card.
